// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (id, title, url, description, created_at, updated_at, published_at, feed_id)
VALUES ($1, $2, $3, $4,  $5, $6, $7, $8)
`

type CreatePostParams struct {
	ID          string
	Title       string
	Url         string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	PublishedAt sql.NullTime
	FeedID      sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const getPostForUser = `-- name: GetPostForUser :many
SELECT id, title, url, description, created_at, updated_at, published_at, feed_id from posts
WHERE feed_id IN (
    SELECT feed_id FROM feed_follows WHERE user_id = (
        SELECT id FROM users WHERE name = $1
    )
)
ORDER BY created_at DESC
LIMIT $2
`

type GetPostForUserParams struct {
	Name  string
	Limit int32
}

func (q *Queries) GetPostForUser(ctx context.Context, arg GetPostForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostForUser, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
